---
# tasks file for roles/runeron.docker

- name: uninstall older versions of docker
  become: True
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: update cache
  become: True
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install dependencies
  become: True
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - software-properties-common
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
    - apt-transport-https
    - ca-certificates
    - curl

- name: add docker key
  become: True
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add repository
  become: True
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: install docker
  become: True
  apt:
    name: docker-ce
    state: present
