---

- name: preparation | check for pip installation
  become: no
  stat:
    path: '~/.local/bin/pip'
  register: st_pip

- name: preparation | install pre-requirements
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - build-essential
    - python-minimal
    - krb5-user
    - python-dev
    - libssl-dev
    - libffi-dev
    - libkrb5-dev
    
- name: preparation | download files
  become: no
  get_url:
    url: 'https://bootstrap.pypa.io/get-pip.py'
    dest: '/tmp/get-pip.py'
  when: not st_pip.stat.exists

- name: installation | execute pip installation
  become: no
  command: 'python /tmp/get-pip.py --user'
  when: not st_pip.stat.exists

- name: configuration | add pip path to bashrc
  become: no
  command: 'echo "PATH=\$PATH:~/.local/bin" >> ~/.bashrc'
  when: not st_pip.stat.exists

- name: configuration | source bashrc
  become: no
  shell: 'source ~/.bashrc'
  args:
    executable: '/bin/bash'
  when: not st_pip.stat.exists
    
- name: installation | add ansible and tools (pip)
  become: no
  pip:
    name: '{{ item }}'
    extra_args: '--user'
    state: present
  with_items:
    - ansible
    - pywinrm[kerberos]
    - pywinrm[credssp]
    - pysphere
