---

- name: apt installation | requirements
  stat:
    path: '~/.local/bin/pip'
  register: st_pip

- name: preparation | install pre-requirements
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - python-minimal

- name: pip preparation | download files
  become: no
  get_url:
    url: 'https://bootstrap.pypa.io/get-pip.py'
    dest: '/tmp/get-pip.py'
  when: not st_pip.stat.exists

- name: pip installation | execute python script
  become: no
  command: 'python /tmp/get-pip.py --user'
  when: not st_pip.stat.exists

- name: configuration | add pip to bashrc
  become: no
  command: 'echo "PATH=\$PATH:~/.local/bin" >> ~/.bashrc'
  when: not st_pip.stat.exists

- name: pip configuration | source bashrc
  become: no
  shell: 'source ~/.bashrc'
  args:
    executable: '/bin/bash'
  when: not st_pip.stat.exists
    

- name: pip installation | ansible
  become: no
  pip:
    name: ansible
    extra_args: '--user'
    state: present
