---
# tasks file for roles/runeron.nodejs

- name: install nodejs
  become: True
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - nodejs
    - npm

