---
- name: Upgrade apt-hosts
  hosts: all
  remote_user: wlab
  become: yes
  become_method: sudo

  pre_tasks:
    - include: ../tasks/bootstrap-ubuntu.yml

  tasks:
    - name: APT - Update cache
      apt:
        update_cache: yes
        cache_valid_time: 86400 # 24h

    - name: APT - Upgrade all packages
      apt:
        upgrade: yes

    - name: APT - Cleanup & remove
      apt:
        autoremove: yes
        autoclean: yes
